name: Python CI

on:
  push:
    branches: [ main, master, '**' ]
  pull_request:
    branches: [ '**' ]

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .[dev]

      - name: Ruff (lint)
        run: |
          ruff check sigmatiq_card_api/

      - name: Black (format check)
        run: |
          black --check sigmatiq_card_api/

      - name: Pytest
        run: |
          pytest -q

