name: Tests

on:
  push:
  pull_request:

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt pytest pytest-cov pytest-asyncio

      - name: Run unit tests
        run: |
          if [ -d tests ]; then
            pytest tests/ -v --cov=sigmatiq_card_api --cov-report=term-missing
          else
            echo "No tests directory found, skipping tests"
            exit 0
          fi

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install linting tools
        run: |
          python -m pip install --upgrade pip
          pip install black ruff

      - name: Run black check
        run: |
          black --check sigmatiq_card_api/

      - name: Run ruff
        run: |
          ruff check sigmatiq_card_api/
